name: kafka-images
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
sonarqube:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: [
    'confluentinc/cp-server-connect',
    'confluentinc/cp-server-connect-base',
    'confluentinc/cp-kafka-connect',
    'confluentinc/cp-kafka-connect-base',
    'confluentinc/cp-kafka',
    'confluentinc/confluent-local',
    'confluentinc/cp-server',
    'confluentinc/cp-server-native'
  ]
  community_docker_repos: [
    'confluentinc/cp-kafka-connect',
    'confluentinc/cp-kafka-connect-base',
    'confluentinc/cp-kafka',
    'confluentinc/confluent-local'
  ]
  community_maven_modules: [
    'kafka-connect',
    'kafka-connect-base',
    'kafka',
    'local'
  ]
  maven_phase: 'verify'
  maven_skip_deploy: true
  build_arm: true
  os_types: ['ubi9']
  nano_version: true
  use_packages: true
  cp_images: true
  sign_images: true
  pip_install_package: 'tox==3.28.0'
  push_latest: true
  tasks:
    - name: cp-dockerfile-build
      branch: master
      pipeline_file: .semaphore/cp_dockerfile_build.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
        - name: PACKAGES_URL
          required: true
        - name: PACKAGES_MAVEN_URL
          required: true
        - name: PACKAGING_BUILD_NUMBER
          required: true
        - name: ALLOW_UNSIGNED
          required: true
          default_value: 'False'
          options:
            - 'True'
            - 'False'
        - name: CONFLUENT_DEB_VERSION
          required: true
          default_value: '1'
        - name: SKIP_COMMUNITY
          required: false
          default_value: 'False'
          description: 'Skip building community docker images'
          options:
            - 'True'
            - 'False'  
    - name: cp-dockerfile-promote
      branch: master
      pipeline_file: .semaphore/cp_dockerfile_promote.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
        - name: IMAGE_REVISION
          required: true
          default_value: '1'
        - name: UPDATE_LATEST_TAG
          required: true
        - name: PACKAGING_BUILD_NUMBER
          required: true
        - name: PROMOTE_OS_TYPE
          required: true
          options:
            - 'deb'
            - 'ubi'
        - name: SKIP_COMMUNITY
          required: false
          default_value: 'False'
          description: 'Skip publishing community docker images'
          options:
            - 'True'
            - 'False'    
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent.kafka-images/kafka-images-parent
    - maven-snapshots/maven/io.confluent.kafka-images/cp-zookeeper
    - maven-snapshots/maven/io.confluent.kafka-images/cp-server-connect-base
    - maven-snapshots/maven/io.confluent.kafka-images/cp-server-connect
    - maven-snapshots/maven/io.confluent.kafka-images/cp-server
    - maven-snapshots/maven/io.confluent.kafka-images/cp-server-native
    - maven-snapshots/maven/io.confluent.kafka-images/confluent-local
    - maven-snapshots/maven/io.confluent.kafka-images/cp-kafka-connect-base
    - maven-snapshots/maven/io.confluent.kafka-images/cp-kafka-connect
    - maven-snapshots/maven/io.confluent.kafka-images/cp-kafka
    - maven-snapshots/maven/io.confluent.kafka-images/cp-enterprise-kafka
