Configuration:
  name: "Log4j2"

  Appenders:
    Console:
      name: STDERR
      target: SYSTEM_ERR
      PatternLayout:
        Pattern: "[%d] %p %m (%c)%n"

  Loggers:
    Root:
      level: "WARN"
      AppenderRef:
        - ref: STDERR