version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  cp-server:
    image: confluentinc/cp-server:7.6.0
    hostname: cp-server
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "8090:8090"    # Admin REST API port (needed!)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-server:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    depends_on:
      - cp-server
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://cp-server:9092

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.6.0
    depends_on:
      - cp-server
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://cp-server:9092
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
