name: Build Confluent/Kafka Image

on:
  pull_request

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to ci-registry
        env:
          KEY_ID: ${{ secrets.OPS_C3CI_DOCKER_CI_USER }}
        run: |
          echo KEY_ID
          docker login ${{secrets.OPS_C3CI_DOCKER_CI_REGISTRY_URL}} -u ${{secrets.OPS_C3CI_DOCKER_CI_USER}} -p ${{secrets.OPS_C3CI_DOCKER_CI_PASSWORD}} 
          docker login ${{secrets.OPS_C3CI_DOCKER_CI_REGISTRY_URL}} -u ${{secrets.OPS_C3CI_DOCKER_CI_USER}} -p ${{secrets.OPS_C3CI_DOCKER_CI_PASSWORD}}
     
            

     